### ISSUE TITLE
Sonoff D1 not dimming

### ISSUE THREAD

**Issue by Gmeiburg88** [thepotterfamily/homebridge-ewelink-beta#4]
Hi there,

I would like to start and say well done on the project, I know its a fork but you are putting in allot of effort to make it great. So far all the devices are working as expected, the only one I am having trouble with is the dimmer (D1) I can switch it on and off but cat set the level of brightness. 

I have switched on debugging and can see that its sending the brightness request but then it returns with a 504 error.

Thank you for the fork!

**Comment by thepotterfamily** [comment]
Hi,
Thanks for your comments.
Please try updating to 0.12.2 to see if this has sorted the issue.
Perhaps a Homebridge restart too :)
Ben

**Comment by Gmeiburg88** [comment]
Thank you so much for the quick response. I am just waiting for it to shop up in the Hoobs update then I will give feedback.

Thank you once again

**Comment by thepotterfamily** [comment]
Don’t suppose you have other devices like the fan or thermostat? 🤔

**Comment by Gmeiburg88** [comment]
I can get some if you want me to help test it :-)  I have a couple of the 2 and 3 hall switches, the dimmer and the power monitor Pow R2. All of them are RF as well. I just ordered a basic R3 as well.  

Ok I have updated to 0.12.2 and reboot the bridge. its still giving me a 504 error :-(

**Comment by thepotterfamily** [comment]
would you be happy to email me? bwp91@icloud.com

**Comment by Gmeiburg88** [comment]
Thank you so much! version 0.12.3 worked thank you for your efforts and the trouble shooting you are 1 in a mil!

**Comment by thepotterfamily** [comment]
Pleasure :)
