### ISSUE TITLE
Error starting homebridge

### ISSUE THREAD

**Issue by motogon** [thepotterfamily/homebridge-ewelink-beta#5]
Error starting homebridge after install homebridge-ewelink-beta.

my conf

 {
            "name": "eWeLink",
            "countryCode": "07",
            "email": "xxxxxxxx.ru",
            "password": "xxxxxxxx",
            "platform": "eWeLink"
        }

log :
[2020-6-25 4:52:08 PM] TypeError: Cannot read property 'set' of undefined
Jun 25 13:52:08 dend homebridge[1997]:     at eWeLink.configureAccessory (/usr/lib/node_modules/homebridge-ewelink-beta/index.js:802:25)
Jun 25 13:52:08 dend homebridge[1997]:     at cachedPlatformAccessories.cachedPlatformAccessories.filter.accessory (/usr/lib/node_modules/homebridge/src/server.ts:307:25)
Jun 25 13:52:08 dend homebridge[1997]:     at Array.filter (<anonymous>)
Jun 25 13:52:08 dend homebridge[1997]:     at Server.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:270:69)
Jun 25 13:52:08 dend homebridge[1997]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:158:10)
Jun 25 13:52:08 dend homebridge[1997]:     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
Jun 25 13:52:08 dend homebridge[1997]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 25 13:52:08 dend homebridge[1997]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Jun 25 13:52:08 dend homebridge[1997]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Jun 25 13:52:08 dend homebridge[1997]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 25 13:52:08 dend homebridge[1997]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 25 13:52:08 dend homebridge[1997]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jun 25 13:52:08 dend homebridge[1997]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Jun 25 13:52:08 dend homebridge[1997]:     at startup (internal/bootstrap/node.js:283:19)
Jun 25 13:52:08 dend homebridge[1997]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Jun 25 13:52:08 dend homebridge[1997]: [2020-6-25 4:52:08 PM] Got SIGTERM, shutting down Homebridge...

**Comment by thepotterfamily** [comment]
Hi,
In your config please change "email" to "username" so:
```
{
"name": "eWeLink",
"countryCode": "07",
"username": "xxxxxxxx.ru",
"password": "xxxxxxxx",
"platform": "eWeLink"
}
```
Then restart Homebridge and see if that works.

**Comment by motogon** [comment]
after replacing with username, the error in the log disappeared.
homebridge started successfully.
Jun 25 15:19:20 dend homebridge [4900]: [2020-6-25 6:19:20 PM] [eWeLink] [1] eWeLink devices were loaded from the Homebridge cache and will be refreshed.
Jun 25 15:19:20 dend homebridge [4900]: [2020-6-25 6:19:20 PM] [eWeLink] [1] primary devices were loaded from your eWeLink account.
Jun 25 15:19:20 dend homebridge [4900]: [2020-6-25 6:19:20 PM] [eWeLink] [0] groups were loaded from the Homebridge configuration.
Jun 25 15:19:20 dend homebridge [4900]: [2020-6-25 6:19:20 PM] [eWeLink] Plugin initialization has been successful.

Dimmer attached in eWeLink - added to Homekit.

But a new problem: the status of the dimer in Homekit is reflected and changed, with changes made in eWeLink. But any changes with a dimer in Homekit are not made by the device.

**Comment by thepotterfamily** [comment]
Can I ask which dimmer device you have? Is it the D1 dimmer?

**Comment by motogon** [comment]
using this dimer

https://www.aliexpress.com/item/4000159552622.html?spm=a2g0s.9042311.0.0.264d33edF3aQce&_ga=2.116411782.144377579.1593080282-699475450.1578127662

**Comment by thepotterfamily** [comment]
Ahh I see.
I don’t think this is a sonoff device which is mainly what this package is for.
I understand that you use ewelink to control this device, but sonoff isn’t the only brand that uses ewelink.
I can definitely look into implementing this device so you can have dimmer control :)

**Comment by thepotterfamily** [comment]
In your ewelink app, would you go to the device, go to the settings and tell me what is says for “Manufacturer” and “Model” ?

**Comment by motogon** [comment]
![2020-06-25_20-01-53](https://user-images.githubusercontent.com/12997195/85765671-fe34da80-b71e-11ea-8acf-534b043e70fe.png)

**Comment by thepotterfamily** [comment]
Hi again,
thanks for that.
i may or may not have fixed this (as i don’t own the device i can’t really test)
but please try updating, removing the device from the homebridge cache, restarting homebridge to see if it works?
thanks

**Comment by motogon** [comment]
Hi . 
it works now

thank
